export const events = [
  {
    id: "ET001",
    eventDate: "WED 01-10-2023",
    eventHead: "event Heading 1 ",
    eventFile: "ypaEvent.pdf",
    event: "this is event 1",
    isNew: true,
  },
  {
    id: "ET002",
    eventDate: "THU 02-10-2023",
    eventHead: "event Heading 2",
    eventFile: "ypaEvent.pdf",
    event: "this is event 2",
    isNew: true,
  },
  {
    id: "ET003",
    eventDate: "FRI 03-10-2023",
    eventHead: "event Heading 3",
    eventFile: "ypaEvent.pdf",
    event: "this is event 3",
    isNew: false,
  },
  {
    id: "ET004",
    eventDate: "SAT 04-10-2023",
    eventHead: "event Heading 4",
    eventFile: "ypaEvent.pdf",
    event: "this is event 4",
    isNew: false,
  },
  {
    id: "ET005",
    eventDate: "SAT 05-10-2023",
    eventHead: "event Heading 5",
    eventFile: "ypaEvent.pdf",
    event: "this is event 5",
    isNew: false,
  },
  {
    id: "ET006",
    eventDate: "SAT 06-10-2023",
    eventHead: "event Heading 6",
    eventFile: "ypaEvent.pdf",
    event: "this is event 6",
    isNew: false,
  },
  {
    id: "ET007",
    eventDate: "SAT 07-10-2023",
    eventHead: "event Heading 7",
    eventFile: "ypaEvent.pdf",
    event: "this is event 7",
    isNew: false,
  },
  {
    id: "ET008",
    eventDate: "SAT 08-10-2023",
    eventHead: "event Heading 8",
    eventFile: "ypaEvent.pdf",
    event: "this is event 8",
    isNew: false,
  },
  {
    id: "ET009",
    eventDate: "SAT 09-10-2023",
    eventHead: "event Heading 9",
    eventFile: "ypaEvent.pdf",
    event: "this is event 9",
    isNew: false,
  },
  {
    id: "010",
    eventDate: "SAT 10-10-2023",
    eventHead: "event Heading 10",
    eventFile: "ypaEvent.pdf",
    event: "this is event 10",
    isNew: false,
  },
  {
    id: "011",
    eventDate: "SAT 11-10-2023",
    eventHead: "event Heading 11",
    eventFile: "ypaEvent.pdf",
    event: "this is event 11",
    isNew: false,
  },
];
