export const news = [
  {
    id: "001",
    target: "https://Target.Link",
    newsDate: "WED 01-10-2023",
    newsHead: "news Heading 1 ",
    news: "this is news 1",
    isNew: true,
  },
  {
    id: "002",
    target: "https://Target.Link",
    newsDate: "THU 02-10-2023",
    newsHead: "news Heading 2",
    news: "this is news 2 ",
    isNew: true,
  },
  {
    id: "003",
    target: "https://Target.Link",
    newsDate: "FRI 03-10-2023",
    newsHead: "news Heading 3",
    news: "this is news 3",
    isNew: false,
  },
  {
    id: "004",
    target: "https://Target.Link",
    newsDate: "SAT 04-10-2023",
    newsHead: "news Heading 4",
    news: "this is news 4",
    isNew: false,
  },
  {
    id: "005",
    target: "https://Target.Link",
    newsDate: "SAT 05-10-2023",
    newsHead: "news Heading 5",
    news: "this is news 5",
    isNew: false,
  },
  {
    id: "006",
    target: "https://Target.Link",
    newsDate: "SAT 06-10-2023",
    newsHead: "news Heading 6",
    news: "this is news 6",
    isNew: false,
  },
  {
    id: "007",
    target: "https://Target.Link",
    newsDate: "SAT 07-10-2023",
    newsHead: "news Heading 7",
    news: "this is news 7",
    isNew: false,
  },
  {
    id: "008",
    target: "https://Target.Link",
    newsDate: "SAT 08-10-2023",
    newsHead: "news Heading 8",
    news: "this is news 8",
    isNew: false,
  },
  {
    id: "009",
    target: "https://Target.Link",
    newsDate: "SAT 09-10-2023",
    newsHead: "news Heading 9",
    news: "this is news 9",
    isNew: false,
  },
  {
    id: "010",
    target: "https://Target.Link",
    newsDate: "SAT 10-10-2023",
    newsHead: "news Heading 10",
    news: "this is news 10",
    isNew: false,
  },
  {
    id: "011",
    target: "https://Target.Link",
    newsDate: "SAT 11-10-2023",
    newsHead: "news Heading 11",
    news: "this is news 11",
    isNew: false,
  },
];
